apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: nats-charts
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/saivamshi465/nats.git
  ref:
    branch: main
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats-charts
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./nats/
      version: "7.1.19"
      sourceRef:
        kind: GitRepository
        name: nats-charts
        namespace: flux-system
      interval: 1m
